---
framework:
- all
quiet: true
skip-check:
- CKV_GIT_1   # Ensure GitHub repository is Private
- CKV_GIT_4   # Ensure GitHub Actions secrets are encrypted
- CKV_GIT_5   # GitHub pull requests should require at least 2 approvals
