---
compact: true
deep-analysis: true
framework:
- all
quiet: true
skip-check:
# Skip cloud provider specific checks since we're on bare metal
- CKV_AWS_.*
- CKV_AZURE_.*
- CKV_GCP_.*
# Ensure GitHub repository is Private (we have public repos)
- CKV_GIT_1
# Ensure GitHub repository has vulnerability alerts enabled (cannot enable vuln. alerts on non-enterprise private repos)
- CKV_GIT_3
# Ensure GitHub Actions secrets are encrypted
- CKV_GIT_4
# GitHub pull requests should require at least 2 approvals (its just me, bro)
- CKV_GIT_5
- CKV_DOCKER_.*
- CKV2_GHA_1
# Ensure GitHub branch protection rules requires signed commits - few repos using semantic-release can't force
# signed commits, we'll migrate off of semantic-release to release-please.
- CKV_GIT_6
