# openclaw: 8 explicit models; MCP via explicit object_permission (Shape B, this module's
# REST seam) across 5 servers, each with its own bespoke tool allowlist — NOT a copy of n8n's
# profile (compare the grafana list here to key-n8n.tf's: openclaw's is far broader, including
# incident management, Athena/ClickHouse/Snowflake, Sift, and on-call). Transcribed verbatim
# from the owner-supplied live-key-config-verbatim.json (GET /key/list on the homelab proxy,
# 2026-08-10) and verified programmatically against that source — see the PR description/report
# for the verification method and counts.
module "openclaw" {
  source = "../../modules/litellm-virtual-key"

  consumer = "openclaw"
  models = [
    "openai/gpt-mini-latest",
    "openai/gpt-5-nano",
    "google/gemini-3.5-flash-lite",
    "deepseek/deepseek-v4-pro",
    "deepseek/deepseek-v4-flash",
    "openai/text-embedding-3-small",
    "openai/gpt-4o-mini",
    "text-embedding-3-small",
  ]

  mcp_server_aliases = [
    "context7",
    "playwright",
    "grafana",
    "home_assistant",
    "github",
  ]
  mcp_tool_permissions = {
    context7 = [
      "resolve-library-id",
      "get-library-docs",
    ]
    playwright = [
      "browser_close",
      "browser_resize",
      "browser_console_messages",
      "browser_handle_dialog",
      "browser_evaluate",
      "browser_file_upload",
      "browser_find",
      "browser_fill_form",
      "browser_press_key",
      "browser_type",
      "browser_navigate",
      "browser_navigate_back",
      "browser_network_requests",
      "browser_network_request",
      "browser_run_code_unsafe",
      "browser_take_screenshot",
      "browser_snapshot",
      "browser_click",
      "browser_hover",
      "browser_select_option",
      "browser_tabs",
      "browser_wait_for",
    ]
    github = [
      "actions_get",
      "actions_list",
      "add_issue_comment",
      "create_gist",
      "get_code_quality_finding",
      "get_code_scanning_alert",
      "get_commit",
      "get_dependabot_alert",
      "get_file_contents",
      "get_gist",
      "get_global_security_advisory",
      "get_job_logs",
      "get_label",
      "get_latest_release",
      "get_me",
      "get_release_by_tag",
      "get_repository_tree",
      "get_secret_scanning_alert",
      "get_tag",
      "issue_read",
      "issue_write",
      "list_branches",
      "list_code_scanning_alerts",
      "list_commits",
      "list_dependabot_alerts",
      "list_gists",
      "list_global_security_advisories",
      "list_issue_fields",
      "list_issue_types",
      "list_issues",
      "list_label",
      "list_org_repository_security_advisories",
      "list_pull_requests",
      "list_releases",
      "list_repository_collaborators",
      "list_repository_security_advisories",
      "list_secret_scanning_alerts",
      "list_starred_repositories",
      "pull_request_read",
      "search_code",
      "search_commits",
      "search_issues",
      "search_orgs",
      "search_pull_requests",
      "search_repositories",
      "search_users",
      "sub_issue_write",
      "add_reply_to_pull_request_comment",
    ]
    grafana = [
      "add_activity_to_incident",
      "alerting_manage_routing",
      "alerting_manage_rules",
      "analyze_loki_labels",
      "check_datasources_health",
      "create_datasource",
      "create_incident",
      "create_snapshot",
      "describe_athena_table",
      "describe_clickhouse_table",
      "describe_snowflake_table",
      "find_error_pattern_logs",
      "find_slow_requests",
      "generate_deeplink",
      "get_alert_group",
      "get_assertions",
      "get_current_oncall_users",
      "get_dashboard_by_uid",
      "get_dashboard_panel_queries",
      "get_dashboard_property",
      "get_dashboard_summary",
      "get_datasource",
      "get_incident",
      "get_oncall_shift",
      "get_panel_image",
      "get_sift_analysis",
      "get_sift_investigation",
      "get_snapshot",
      "list_alert_groups",
      "list_athena_catalogs",
      "list_athena_databases",
      "list_athena_tables",
      "list_clickhouse_tables",
      "list_cloudwatch_dimensions",
      "list_cloudwatch_metrics",
      "list_cloudwatch_namespaces",
      "list_datasources",
      "list_graphite_metrics",
      "list_graphite_tags",
      "list_incidents",
      "list_loki_label_names",
      "list_loki_label_values",
      "list_oncall_schedules",
      "list_oncall_teams",
      "list_oncall_users",
      "list_prometheus_label_names",
      "list_prometheus_label_values",
      "list_prometheus_metric_metadata",
      "list_prometheus_metric_names",
      "list_provisioning_repositories",
      "list_pyroscope_label_names",
      "list_pyroscope_label_values",
      "list_pyroscope_profile_types",
      "list_sift_investigations",
      "list_snapshots",
      "list_snowflake_tables",
      "query_athena",
      "query_clickhouse",
      "query_cloudwatch",
      "query_elasticsearch",
      "query_graphite",
      "query_graphite_density",
      "query_influxdb",
      "query_loki_logs",
      "query_loki_patterns",
      "query_loki_stats",
      "query_prometheus",
      "query_prometheus_histogram",
      "query_pyroscope",
      "query_quickwit",
      "query_snowflake",
      "run_panel_query",
      "search_dashboards",
      "search_folders",
      "update_dashboard",
      "update_datasource",
      "validate_provisioning_file",
    ]
    home_assistant = [
      "ha_get_addon",
      "ha_manage_addon",
      "ha_list_floors_areas",
      "ha_set_area_or_floor",
      "ha_get_blueprint",
      "ha_import_blueprint",
      "ha_report_issue",
      "ha_config_get_calendar_events",
      "ha_config_remove_calendar_event",
      "ha_config_set_calendar_event",
      "ha_get_camera_image",
      "ha_config_get_category",
      "ha_config_remove_category",
      "ha_config_set_category",
      "ha_manage_custom_tool",
      "ha_config_get_automation",
      "ha_config_set_automation",
      "ha_config_get_dashboard",
      "ha_config_set_dashboard",
      "ha_config_list_helpers",
      "ha_config_get_scene",
      "ha_config_set_scene",
      "ha_config_get_script",
      "ha_config_set_script",
      "ha_manage_energy_prefs",
      "ha_get_entity",
      "ha_remove_entity",
      "ha_set_entity",
      "ha_config_list_groups",
      "ha_config_remove_group",
      "ha_config_set_group",
      "ha_get_hacs_info",
      "ha_manage_hacs",
      "ha_get_history",
      "ha_get_integration",
      "ha_set_integration",
      "ha_config_get_label",
      "ha_config_remove_label",
      "ha_config_set_label",
      "ha_manage_radio",
      "ha_get_device",
      "ha_set_device",
      "ha_config_delete_dashboard_resource",
      "ha_config_list_dashboard_resources",
      "ha_config_set_dashboard_resource",
      "ha_get_overview",
      "ha_get_state",
      "ha_search",
      "ha_bulk_control",
      "ha_call_event",
      "ha_call_service",
      "ha_get_operation_status",
      "ha_list_services",
      "ha_get_system_health",
      "ha_reload_core",
      "ha_restart",
      "ha_manage_theme",
      "ha_get_todo",
      "ha_remove_todo_item",
      "ha_set_todo_item",
      "ha_get_automation_traces",
      "ha_manage_updates",
      "ha_get_logs",
      "ha_eval_template",
      "ha_get_entity_exposure",
      "ha_manage_pipeline",
      "ha_config_set_yaml",
      "ha_get_zone",
      "ha_remove_zone",
      "ha_set_zone",
      "ha_manage_backup",
      "ha_get_skill_guide",
    ]
  }

  allowed_routes = [
    "llm_api_routes",
  ]
  metadata = {
    tag_rpm_limit               = jsonencode({})
    throttle_on_budget_exceeded = jsonencode(false)
  }

  bitwarden_project_id = var.bitwarden_project_id
  litellm_api_base     = var.litellm_api_base
  litellm_master_key   = var.litellm_master_key
}
