---
# yamllint disable rule:line-length
name: lint

on:
  pull_request:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    outputs:
      actions_any_changed: ${{ steps.changed-files-yaml.outputs.actions_any_changed }}
      actions_all_changed_files: ${{ steps.changed-files-yaml.outputs.actions_all_changed_files}}
      renovate_any_changed: ${{ steps.changed-files-yaml.outputs.renovate_any_changed }}
      renovate_all_changed_files: ${{ steps.changed-files-yaml.outputs.renovate_all_changed_files}}
      shellscripts_any_changed: ${{ steps.changed-files-yaml.outputs.shellscripts_any_changed }}
      shellscripts_all_changed_files: ${{ steps.changed-files-yaml.outputs.shellscripts_all_changed_files}}
      terraform_any_changed: ${{ steps.changed-files-yaml.outputs.terraform_any_changed }}
      terraform_all_changed_files: ${{ steps.changed-files-yaml.outputs.terraform_all_changed_files}}
      terraform_dirs: ${{ steps.determine-tf-dirs.outputs.dirs }}
      yaml_any_changed: ${{ steps.changed-files-yaml.outputs.yaml_any_changed }}
      yaml_all_changed_files: ${{ steps.changed-files-yaml.outputs.yaml_all_changed_files}}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 1

    - name: Determine what files types have changed
      id: changed-files-yaml
      uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45
      with:
        files_yaml: |
          actions:
          - .github/workflows/**
          renovate:
          - .github/renovate.json
          - .github/renovate/**
          shellscripts:
          - '**.sh'
          terraform:
          - modules/**
          - workspaces/**
          - '**.tf'
          - '**/.terraform-version'
          - '**/.terraform.lock.hcl'
          - '.tflint.hcl'
          yaml:
          - '**.yaml'

    - name: Determine Terraform directories to validate
      id: determine-tf-dirs
      # yamllint disable-line rule:indentation
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          # For workflow_dispatch, validate all terraform directories
          TF_DIRS=$(find workspaces modules -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')
        elif [[ "${{ steps.changed-files-yaml.outputs.terraform_any_changed }}" == "true" ]]; then
          # For pull requests, check which files changed
          CHANGED_FILES="${{ steps.changed-files-yaml.outputs.terraform_all_changed_files }}"
          MODULE_CHANGES=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep '^modules/' || true)
          WORKSPACE_CHANGES=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep '^workspaces/' || true)

          # If modules changed, need to validate all workspaces and the changed modules
          if [[ -n "$MODULE_CHANGES" ]]; then
            # Get all workspaces
            WORKSPACES=$(find workspaces -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort)

            # Get changed module directories
            CHANGED_MODULES=$(echo "$MODULE_CHANGES" | grep -o 'modules/[^/]*' | sort | uniq)

            # Combine workspaces and changed modules
            TF_DIRS=$(echo "$WORKSPACES" $'\n' "$CHANGED_MODULES" | sort | uniq | jq -R -s -c 'split("\n") | map(select(length > 0))')

            echo "Module changes detected, validating all workspaces and changed modules"
          else
            # Otherwise only validate affected workspaces
            TF_DIRS=$(echo "$WORKSPACE_CHANGES" | grep -o 'workspaces/[^/]*' | sort | uniq | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "Workspace-specific changes detected, validating only affected workspaces"
          fi
        else
          echo "TF_DIRS=[]" >> $GITHUB_OUTPUT
          echo "No Terraform changes detected"
        fi
        echo "dirs=$TF_DIRS" >> $GITHUB_OUTPUT

  commit-messages:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ppat/github-workflows/.github/workflows/lint-commit-messages.yaml@main
    with:
      git_ref: ${{ github.head_ref }}
      fetch_depth: ${{ github.event.pull_request.commits }}
      from: ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
      to: ${{ github.event.pull_request.head.sha }}

  github-actions:
    needs: [detect-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.actions_any_changed == 'true' }}
    uses: ppat/github-workflows/.github/workflows/lint-github-actions.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name == 'workflow_dispatch' && 'ALL' || needs.detect-changes.outputs.actions_all_changed_files }}

  pre-commit:
    uses: ppat/github-workflows/.github/workflows/lint-pre-commit.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}

  renovate-config-check:
    needs: [detect-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.renovate_any_changed == 'true' }}
    uses: ppat/github-workflows/.github/workflows/lint-renovate-config-check.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name == 'workflow_dispatch' && 'ALL' || needs.detect-changes.outputs.renovate_all_changed_files }}

  shellcheck:
    needs: [detect-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.shellscripts_any_changed == 'true' }}
    uses: ppat/github-workflows/.github/workflows/lint-shellcheck.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name == 'workflow_dispatch' && 'ALL' || needs.detect-changes.outputs.shellscripts_all_changed_files }}

  terraform:
    needs: [detect-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.terraform_any_changed == 'true' }}
    uses: ppat/github-workflows/.github/workflows/lint-terraform.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      tf_dirs: ${{ needs.detect-changes.outputs.terraform_dirs }}

  yaml:
    needs: [detect-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.yaml_any_changed == 'true' }}
    uses: ppat/github-workflows/.github/workflows/lint-yaml.yaml@main
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name == 'workflow_dispatch' && 'ALL' || needs.detect-changes.outputs.yaml_all_changed_files }}
