---
# yamllint disable rule:line-length
name: scan-scheduled

on:
  schedule:
  - cron: '0 0 */7 * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan-scheduled:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
        persist-credentials: false

    - name: Run Trivy
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        hide-progress: true
        format: 'sarif'
        exit-code: '0'
        trivy-config: trivy.yaml
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Checkov scan
      uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7
      with:
        config_file: .checkov.yaml
        output_format: cli,sarif
        output_file_path: console,checkov-results.sarif

    - name: Upload Checkov scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
      if: always()
      with:
        sarif_file: checkov-results.sarif
